// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rota_LivreWEB_API.Data;

#nullable disable

namespace Rota_LivreWEB_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209211425_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rota_LivreWEB_API.Models.Avaliacao", b =>
                {
                    b.Property<int>("id_avaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_avaliacao"));

                    b.Property<DateTime>("data_feedback")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_passeio")
                        .HasColumnType("integer");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<string>("nome_completo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("nota")
                        .HasColumnType("integer");

                    b.HasKey("id_avaliacao");

                    b.HasIndex("id_passeio");

                    b.HasIndex("id_usuario");

                    b.ToTable("Avaliacao");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.Categoria", b =>
                {
                    b.Property<int>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_categoria"));

                    b.Property<string>("img")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipo_categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_categoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.CurtidaPasseio", b =>
                {
                    b.Property<int>("id_curtida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_curtida"));

                    b.Property<int>("id_passeio")
                        .HasColumnType("integer");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.HasKey("id_curtida");

                    b.HasIndex("id_passeio");

                    b.HasIndex("id_usuario");

                    b.ToTable("CurtidaPasseio");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.Endereco", b =>
                {
                    b.Property<int>("id_endereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_endereco"));

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("cep")
                        .HasColumnType("integer");

                    b.Property<string>("complemento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_passeio")
                        .HasColumnType("integer");

                    b.Property<string>("nome_rua")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("numero_rua")
                        .HasColumnType("integer");

                    b.HasKey("id_endereco");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.Funcionario", b =>
                {
                    b.Property<int>("id_funcionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_funcionario"));

                    b.Property<string>("nome_funcionario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_funcionario");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.Grupo", b =>
                {
                    b.Property<int>("id_grupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_grupo"));

                    b.Property<string>("link_grupo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_grupo");

                    b.ToTable("Grupo");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.GrupoPasseio", b =>
                {
                    b.Property<int>("id_grupo_passeio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_grupo_passeio"));

                    b.Property<int>("id_grupo")
                        .HasColumnType("integer");

                    b.Property<int>("id_passeio")
                        .HasColumnType("integer");

                    b.HasKey("id_grupo_passeio");

                    b.HasIndex("id_grupo");

                    b.HasIndex("id_passeio");

                    b.ToTable("GrupoPasseio");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.GrupoUsuario", b =>
                {
                    b.Property<int>("id_grupo_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_grupo_usuario"));

                    b.Property<int>("id_grupo")
                        .HasColumnType("integer");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.HasKey("id_grupo_usuario");

                    b.HasIndex("id_grupo");

                    b.HasIndex("id_usuario");

                    b.ToTable("GrupoUsuario");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.Localizacao", b =>
                {
                    b.Property<int>("id_localizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_localizacao"));

                    b.Property<DateTime>("data_registro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("velocidade")
                        .HasColumnType("double precision");

                    b.HasKey("id_localizacao");

                    b.ToTable("Localizacao");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.Passeio", b =>
                {
                    b.Property<int>("id_passeio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_passeio"));

                    b.Property<bool>("AlternarCurtida")
                        .HasColumnType("boolean");

                    b.Property<int?>("Enderecoid_endereco")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeCurtidas")
                        .HasColumnType("integer");

                    b.Property<bool>("UsuarioJaCurtiu")
                        .HasColumnType("boolean");

                    b.Property<bool>("UsuarioJaPendente")
                        .HasColumnType("boolean");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("funcionamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_categoria")
                        .HasColumnType("integer");

                    b.Property<string>("img_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nome_passeio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_passeio");

                    b.HasIndex("Enderecoid_endereco");

                    b.ToTable("Passeio");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.PasseioFavorito", b =>
                {
                    b.Property<int>("id_favorito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_favorito"));

                    b.Property<int>("id_passeio")
                        .HasColumnType("integer");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.HasKey("id_favorito");

                    b.HasIndex("id_passeio");

                    b.HasIndex("id_usuario");

                    b.ToTable("PasseioFavorito");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.PasseioFuncionario", b =>
                {
                    b.Property<int>("id_passeio_funcionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_passeio_funcionario"));

                    b.Property<int>("id_funcionario")
                        .HasColumnType("integer");

                    b.Property<int>("id_passeio")
                        .HasColumnType("integer");

                    b.HasKey("id_passeio_funcionario");

                    b.HasIndex("id_funcionario");

                    b.HasIndex("id_passeio");

                    b.ToTable("PasseioFuncionario");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.PasseioPendente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("data_adicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_passeio")
                        .HasColumnType("integer");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("id_passeio");

                    b.HasIndex("id_usuario");

                    b.ToTable("passeiospendentes");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.PerguntaSeguranca", b =>
                {
                    b.Property<int>("id_pergunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_pergunta"));

                    b.Property<string>("pergunta_seg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_pergunta");

                    b.ToTable("PerguntaSeguranca");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("ConfirmarSenha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("data_nasc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_pergunta")
                        .HasColumnType("integer");

                    b.Property<string>("nome_completo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("resposta_seg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_usuario");

                    b.HasIndex("id_pergunta");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.UsuarioLocalizacao", b =>
                {
                    b.Property<int>("id_usuario_localizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_usuario_localizacao"));

                    b.Property<int>("id_localizacao")
                        .HasColumnType("integer");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.HasKey("id_usuario_localizacao");

                    b.HasIndex("id_localizacao");

                    b.HasIndex("id_usuario");

                    b.ToTable("UsuarioLocalizacao");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.Avaliacao", b =>
                {
                    b.HasOne("Rota_LivreWEB_API.Models.Passeio", "Passeio")
                        .WithMany()
                        .HasForeignKey("id_passeio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rota_LivreWEB_API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passeio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.CurtidaPasseio", b =>
                {
                    b.HasOne("Rota_LivreWEB_API.Models.Passeio", "Passeio")
                        .WithMany()
                        .HasForeignKey("id_passeio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rota_LivreWEB_API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passeio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.GrupoPasseio", b =>
                {
                    b.HasOne("Rota_LivreWEB_API.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("id_grupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rota_LivreWEB_API.Models.Passeio", "Passeio")
                        .WithMany()
                        .HasForeignKey("id_passeio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Passeio");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.GrupoUsuario", b =>
                {
                    b.HasOne("Rota_LivreWEB_API.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("id_grupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rota_LivreWEB_API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.Passeio", b =>
                {
                    b.HasOne("Rota_LivreWEB_API.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("Enderecoid_endereco")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.PasseioFavorito", b =>
                {
                    b.HasOne("Rota_LivreWEB_API.Models.Passeio", "Passeio")
                        .WithMany()
                        .HasForeignKey("id_passeio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rota_LivreWEB_API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passeio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.PasseioFuncionario", b =>
                {
                    b.HasOne("Rota_LivreWEB_API.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("id_funcionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rota_LivreWEB_API.Models.Passeio", "Passeio")
                        .WithMany()
                        .HasForeignKey("id_passeio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Passeio");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.PasseioPendente", b =>
                {
                    b.HasOne("Rota_LivreWEB_API.Models.Passeio", "Passeio")
                        .WithMany()
                        .HasForeignKey("id_passeio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rota_LivreWEB_API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passeio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.Usuario", b =>
                {
                    b.HasOne("Rota_LivreWEB_API.Models.PerguntaSeguranca", "PerguntaSeguranca")
                        .WithMany()
                        .HasForeignKey("id_pergunta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerguntaSeguranca");
                });

            modelBuilder.Entity("Rota_LivreWEB_API.Models.UsuarioLocalizacao", b =>
                {
                    b.HasOne("Rota_LivreWEB_API.Models.Localizacao", "Localizacao")
                        .WithMany()
                        .HasForeignKey("id_localizacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rota_LivreWEB_API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localizacao");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
